custom_rules:
    - build-configs/state_focused/state-focused.smk
filter:
    division: "Washington"
    group_by_state: "division year"
    group_by_continental: "country year"
    sequences_per_group_state: 20
    sequences_per_group_continental: 20
    min_date: 1950
    min_length: 5000
filter_N450:
    group_by_state: "division year"
    group_by_continental: "country year"
    sequences_per_group_state: 20
    sequences_per_group_continental: 2
    min_date: 1950
    min_length: 400