strain_id_field: "accession"
files:
    exclude: "dropped_strains.txt"
    include_genome: "include_strains_genome.txt"
    include_N450: "include_strains_N450.txt"
    reference: "measles_reference.gb"
    reference_N450: "measles_reference_N450.gb"
    reference_N450_fasta: "measles_reference_N450.fasta"
    colors: "colors.tsv"
    auspice_config: "auspice_config.json"
    auspice_config_N450: "auspice_config_N450.json"
    description: "description.md"
filter:
    group_by: "country year"
    sequences_per_group: 20
    min_date: 1950
    min_length: 5000
filter_N450:
    group_by: "country year"
    subsample_max_sequences: 3000
    min_date: 1950
    min_length: 400
refine:
    coalescent: "opt"
    date_inference: "marginal"
    clock_filter_iqd: 4
ancestral:
    inference: "joint"
tip_frequencies:
    min_date: "2000-01-01"
    max_date: "6M"
    narrow_bandwidth: 0.2
    wide_bandwidth: 0.6
export:
    metadata_columns: "strain division location"
